install.py
inventory
library/cisco_ucs_dns.py
roles/common/tasks/install.yml
roles/common/tasks/main.yml
site.yml
uninstall.py
utils/cisco_ucs.py

Signed-off-by: Vikrant Balyan (vvb) <vvb@cisco.com>

adding the initial structure

---

library/cisco_ucs_role.py

Added module for role configuration

---

library/cisco_ucs_password_profile.py
library/cisco_ucs_password_strength.py
library/cisco_ucs_user.py
library/cisco_ucs_user_locale.py
library/cisco_ucs_user_role.py

Added module to perform configuration related to local user.
- user
- user_role
- user_locale
- password_strength
- password_profile

user module

---

library/cisco_ucs_ntp.py
library/cisco_ucs_timezone.py

Module for timezone and ntp server configuration

Module for timezone and ntp server configuration

---

library/cisco_ucs_locale.py
library/cisco_ucs_locale_org.py

Module for locale configuration

Module for locale configuration

---

library/cisco_ucs_ldap.py
library/cisco_ucs_ldap_group.py
library/cisco_ucs_ldap_group_locale.py
library/cisco_ucs_ldap_group_role.py
library/cisco_ucs_ldap_provider.py
library/cisco_ucs_ldap_provider_group.py
library/cisco_ucs_ldap_provider_group_provider.py
library/cisco_ucs_ldap_provider_group_rules.py

Adds module related to ldap:
- ldap config
- ldap group
- locale for ldap group
- role for ldap group
- ldap provider
- group rules of ldap provider
- ldap provider group
- ldap provider for ldap provider group

LDAP Modules

---

library/cisco_ucs_dns.py

Modifed documentation for dns module.

Modifed documentation for dns module.

---

library/cisco_ucs_ldap.py
library/cisco_ucs_ldap_group.py
library/cisco_ucs_ldap_group_locale.py
library/cisco_ucs_ldap_group_role.py
library/cisco_ucs_ldap_provider.py
library/cisco_ucs_ldap_provider_group.py
library/cisco_ucs_ldap_provider_group_provider.py
library/cisco_ucs_ldap_provider_group_rules.py

Modifed documentation for dns module.

Modified documentation for ldap modules

---

library/cisco_ucs_locale.py
library/cisco_ucs_locale_org.py

Modifed documentation for dns module.

Modified documentation for locale modules

---

library/cisco_ucs_ntp.py
library/cisco_ucs_timezone.py

Modified documentation for ntp and timezone module

---

library/cisco_ucs_role.py

Modified documentation for role module

---

library/cisco_ucs_auth_domain.py
library/cisco_ucs_auth_domain_realm.py
library/cisco_ucs_native_auth.py
library/cisco_ucs_native_auth_console.py
library/cisco_ucs_native_auth_default.py

Adds module related to auth:
- auth domain config
- realm config of auth domain
- native auth config
- native auth default config
- native auth console config

Added modules related to auth config

---

library/cisco_ucs_radius_provider.py
library/cisco_ucs_radius_provider_group.py
library/cisco_ucs_radius_provider_group_provider.py

Adds module related to radius config
- radius provider config
- radius provider group config
- configure radius provider for a radius provider group

Added module for Radius Config

---

library/cisco_ucs_tacacsplus_provider.py
library/cisco_ucs_tacacsplus_provider_group.py
library/cisco_ucs_tacacsplus_provider_group_provider.py

Adds modules for tacacsplus configuration
- tacacsplus provider
- tacacaplus provider group
- configure tacacsplus provider for tacacaplus provider group

added modules for tacacsplus config

---

library/cisco_ucs_syslog_local_console.py
library/cisco_ucs_syslog_local_file.py
library/cisco_ucs_syslog_local_monitor.py
library/cisco_ucs_syslog_remote.py
library/cisco_ucs_syslog_source.py

Adds module related to syslog configuration:
- syslog source
- syslog remote
- syslog local console
- syslog local monitor
- syslog local file

Added module for syslog configuration

---

library/cisco_ucs_snmp.py
library/cisco_ucs_snmp_trap.py
library/cisco_ucs_snmp_user.py

Adds module related to SNMP config.
- snmp config
- snmp user config
- snmp trap config

Added modules related to SNMP config

---

library/cisco_ucs_callhome.py
library/cisco_ucs_callhome_anonymous_reporting.py
library/cisco_ucs_callhome_contact.py
library/cisco_ucs_callhome_policy.py
library/cisco_ucs_callhome_profile.py
library/cisco_ucs_callhome_profile_email.py
library/cisco_ucs_callhome_smtp.py
library/cisco_ucs_callhome_system_inventory.py
library/cisco_ucs_callhome_system_inventory_send_now.py

Adds the module related to callhome config
- callhome contact config
- callhome smtp config
- callhome config
- callhome profile config
- email config for callhome profile
- callhome policy config
- callhome anonymous reporting config
- callhome system inventory config
- sends callhome system inventory 'now'

Added module for Callhome configuration

---

library/cisco_ucs_certificate_request.py
library/cisco_ucs_keyring.py
library/cisco_ucs_trusted_point.py

Adds module to configure
- keyring
- trusted point
- certificate request for a keyring

Added module related to Keyring

---

library/cisco_ucs_password_profile.py
library/cisco_ucs_password_strength.py
library/cisco_ucs_user.py
library/cisco_ucs_user_locale.py
library/cisco_ucs_user_role.py

modified api to add multiple roles to an user

---

library/cisco_ucs_boot_order.py
library/cisco_ucs_boot_policy.py
library/cisco_ucs_boot_security.py

Added modules for boot configuration

---

library/cisco_ucs_power.py

added module to configure server power via service profile

---

README.md
library/ucs_ip_pool.py
library/ucs_lan_connectivity.py
library/ucs_mac_pool.py
library/ucs_san_connectivity.py
library/ucs_vhba_template.py
library/ucs_vlans.py
library/ucs_vnic_template.py
library/ucs_vsans.py
library/ucs_wwn_pool.py
utils/remote_management/ucs.py

UCS modules from the 2.5 Ansible repo to support ongoing development (2.5 is frozen).
Does not support install/uninstall scripts to avoid ongoing maintenance or issues with installed modules.  Use env variables or command line params for use:
ANSIBLE_LIBRARY=./library ANSIBLE_MODULE_UTILS=./utils ansible-playbook ...

UCS module_utils, LAN, and SAN modules from Ansible 2.5

---

library/ucs_vnic_template.py

Will revisit and add integration tests in official Ansible repo

Fix use of redundancy template in vnic

---

library/ucs_service_profile_association.py
library/ucs_uuid_pool.py
utils/module_doc_fragments/ucs.py

ucs doc fragment from ansible repo.
ansible-doc can be used if doc fragment is placed into <ansible python module location>/utils/module_doc_fragments

uuid and service profile association/disassociate modules

---

library/ucs_service_profile_association.py
library/ucs_service_profile_from_template.py
library/ucs_service_profile_template.py

Service profile template (no storage profile support yet).
Service profiles from template.
Service profile association (used on existing service profile).

Service profile template and association.

---

library/ucs_managed_objects.py

See the documentation (ansible-doc) and examples for how managed objects can be specified in a playbook.

Module to directly configure managed objects and their children.

---

dcloud_inventory
group_vars/docker_dcloud
inventory
library/ucs_chassis_profile_from_template.py
library/ucs_chassis_template.py
library/ucs_chassis_zoning.py
roles.yml

updated dcloud inventory and group_vars for use with new role.

Move chassis modules into library.  Example roles for CiscoUcs.ucs 

---

library/ucs_chassis_fw.py

UCS Chassis Firmware Policy

---

library/ucs_chassis_connection.py
library/ucs_chassis_profile_from_template.py
library/ucs_chassis_template.py
library/ucs_chassis_zoning.py

Minor edits to three modules in mo_exists

---

library/ucs_service_profile_template.py

child mo and mo props now checked

check storage profile for prop match.  Add logic to check child mos

---

library/ucs_service_profile_template.py

Add additional checking for inband management config.
This file needs another pass to properly check settings across all the storge/lan/san/pool qualifiers that are optional.

Do not add LsRequirement if no server pool given.  

---

library/ucs_network_control.py

removed duplicate line

---

library/ucs_system_qos.py

Clean up imports and removed unused code

Corrected false positive change with Best Effort

---

Development.md
library/ucs_ip_pool.py

Update allows IP blocks to be managed within an IP pool. Allows multiple IP blocks to be specified.

Add IP block management

---

library/ucs_network_control.py

Added forge option which will help with handle the current error raised when run against UCS mini

Add handling for UCS Mini

---

library/ucs_vlan_to_group.py

VLAN to Group module

---

library/ucs_disk_group_policy.py
library/ucs_mac_pool.py
library/ucs_managed_objects.py
library/ucs_san_connectivity.py
library/ucs_storage_profile.py
library/ucs_timezone.py
library/ucs_uuid_pool.py
library/ucs_vhba_template.py
library/ucs_vlans.py
library/ucs_vnic_template.py
library/ucs_vsans.py
library/ucs_wwn_pool.py

Modules in Ansible devel now certified.

Sync to current Ansible devel branch.  

---

library/ucs_vnic_template.py

Fix issue when requesting vlan absent and vlan is already absent

---

library/ucs_network_control.py

Issue when choosing all-host-vlans as MAC Register Mode

Correct issue on ucs_network_control.py when setting MAC Register Mode
